console.log("My first console project");
var first_name="Aryan";
var last_name="Kishor";
var full_name=first_name.concat(last_name);
console.log(full_name);
var a=10;
var b=5;
var add=a+b;
console.log(add);
var minus=a-b;
console.log(minus);
var divide=a/b;
console.log(divide);
var multiply=a*b;
console.log(multiply);
